apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: 2017-11-01T06:59:48Z
  generation: 4
  labels:
    run: pets
  name: pets
  namespace: cotd
  resourceVersion: "11373"
  selfLink: /apis/extensions/v1beta1/namespaces/cotd/deployments/pets
  uid: 40116aad-bed2-11e7-b286-001fc69bc452
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pets
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: pets
    spec:
      containers:
      - env:
        - name: SELECTOR
          valueFrom:
            configMapKeyRef:
              key: selector
              name: pets-config
        image: stefanopicozzi/pets
        imagePullPolicy: Always
        name: pets
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app-root/src/data/images
          name: pets-images-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pets-images-storage
        persistentVolumeClaim:
          claimName: pets-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-11-01T06:59:48Z
    lastUpdateTime: 2017-11-01T06:59:48Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
