apiVersion: v1
kind: BuildConfig
metadata:
  name: cotdcicdpipeline
  labels:
    name: cotdcicdpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "cotdcicd", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: 
          "node('maven') {\n\
         \n  stage '==> Build&Deploy-In-Development'\n\ 
         \n  openshiftBuild(namespace: 'development', buildConfig: 'cats', showBuildLogs: 'true', waitTime: '300000')\
         \n  stage '==> Verify-In-Development'\n\
         \n  openshiftVerifyDeployment(namespace: 'development', deploymentConfig: 'cats', replicaCount: '1')\
       \n\n  stage '==> Tag-Image-in-Development'\n\
         \n  openshiftTag(namespace: 'development', sourceStream: 'cats', sourceTag: 'latest', destinationStream: 'cats', destinationTag: 'promoteQA')\
       \n\n  stage '==> Deploy-In-Testing' \n\
         \n  openshiftDeploy(namespace: 'testing', deploymentConfig: 'cats', waitTime: '300000')\
       \n\n  stage '==> Scale-In-Testing' \n\
         \n  openshiftScale(namespace: 'testing', deploymentConfig: 'cats', replicaCount: '2', waitTime: '300000')\
         \n  stage '==> Verify-In-Testing'\n\
         \n  openshiftVerifyDeployment(namespace: 'testing', deploymentConfig: 'cats', replicaCount: '2')\
       \n\n}\n"
  output:
  resources:
  postCommit:
